### ISSUE TITLE
New warnings and error messages after updating to the latest Kytos version

### ISSUE THREAD

**Issue by dgarc330** [kytos/kytos#1027]
Hello guys,

Today I installed the new Kytos version and I’m getting some warnings and error messages. I think they have something to do with the topology but I would appreciate your input on this:

Message from the log after starting Kytos:

```
2020-01-21 15:32:56,465 - INFO [kytos.core.logs] (MainThread) Logging config file "/root/python3-jab/etc/kytos/logging.ini" loaded successfully.
2020-01-21 15:32:56,467 - INFO [kytos.core.controller] (MainThread) /root/python3-jab/var/run/kytos
2020-01-21 15:32:56,467 - INFO [kytos.core.controller] (MainThread) Starting Kytos - Kytos Controller
2020-01-21 15:32:56,468 - INFO [kytos.core.controller] (MainThread) Starting TCP server: <kytos.core.atcp_server.KytosServer object at 0x7f331bf18e48>
2020-01-21 15:32:56,469 - INFO [kytos.core.atcp_server] (MainThread) Kytos listening at 0.0.0.0:6653
2020-01-21 15:32:56,469 - INFO [kytos.core.controller] (MainThread) ThreadPool started: <concurrent.futures.thread.ThreadPoolExecutor object at 0x7f331bca2c18>
2020-01-21 15:32:56,470 - INFO [kytos.core.controller] (MainThread) Loading Kytos NApps...
2020-01-21 15:32:56,482 - INFO [kytos.core.napps.napp_dir_listener] (MainThread) NAppDirListener Started...
2020-01-21 15:32:56,486 - INFO [kytos.core.controller] (MainThread) Loading NApp kytos/of_core
2020-01-21 15:32:56,641 - INFO [kytos.core.controller] (MainThread) Loading NApp kytos/flow_manager
2020-01-21 15:32:56,802 - INFO [kytos.napps] (of_core) Running NApp: <Main(of_core, started 139857389160192)>
2020-01-21 15:32:56,812 - INFO [kytos.napps] (flow_manager) Running NApp: <Main(flow_manager, started 139857379981056)>
2020-01-21 15:32:56,816 - INFO [kytos.core.api_server] (MainThread) Started /api/kytos/flow_manager/v2/flows/<dpid> - POST
2020-01-21 15:32:56,819 - INFO [kytos.core.api_server] (MainThread) Started /api/kytos/flow_manager/v2/flows - POST
2020-01-21 15:32:56,821 - INFO [kytos.core.api_server] (MainThread) Started /api/kytos/flow_manager/v2/delete/<dpid> - POST
2020-01-21 15:32:56,826 - INFO [kytos.core.api_server] (MainThread) Started /api/kytos/flow_manager/v2/delete - POST
2020-01-21 15:32:56,828 - INFO [kytos.core.api_server] (MainThread) Started /api/kytos/flow_manager/v2/flows/<dpid> - GET
2020-01-21 15:32:56,829 - INFO [kytos.core.api_server] (MainThread) Started /api/kytos/flow_manager/v2/flows - GET
2020-01-21 15:32:56,829 - INFO [kytos.core.controller] (MainThread) Loading NApp kytos/of_lldp
2020-01-21 15:32:56,835 - INFO [kytos.napps] (of_lldp) Running NApp: <Main(of_lldp, started 139857379981056)>
2020-01-21 15:32:56,836 - INFO [kytos.core.controller] (MainThread) Loading NApp kytos/storehouse
2020-01-21 15:32:56,862 - INFO [kytos.napps.kytos/storehouse] (MainThread) Storehouse NApp started.
2020-01-21 15:32:56,864 - INFO [kytos.napps] (storehouse) Running NApp: <Main(storehouse, started 139857368876800)>
2020-01-21 15:32:56,869 - INFO [kytos.core.api_server] (MainThread) Started /api/kytos/storehouse/v1/<namespace>/<name> - POST
2020-01-21 15:32:56,871 - INFO [kytos.core.api_server] (MainThread) Started /api/kytos/storehouse/v1/<namespace> - POST
2020-01-21 15:32:56,875 - INFO [kytos.core.api_server] (MainThread) Started /api/kytos/storehouse/v1/<namespace>/<box_id> - DELETE
2020-01-21 15:32:56,879 - INFO [kytos.core.api_server] (MainThread) Started /api/kytos/storehouse/v1/<namespace> - GET
2020-01-21 15:32:56,881 - INFO [kytos.core.api_server] (MainThread) Started /api/kytos/storehouse/v1/<namespace>/<box_id> - GET
2020-01-21 15:32:56,885 - INFO [kytos.core.api_server] (MainThread) Started /api/kytos/storehouse/v1/<namespace>/search_by/<filter_option>/<query> - GET
2020-01-21 15:32:56,887 - INFO [kytos.core.api_server] (MainThread) Started /api/kytos/storehouse/v1/<namespace>/<box_id> - PUT, PATCH
2020-01-21 15:32:56,888 - INFO [kytos.core.controller] (MainThread) Loading NApp kytos/topology
2020-01-21 15:32:56,902 - INFO [kytos.napps.kytos/topology] (MainThread) verify data in storehouse for switches.
2020-01-21 15:32:56,906 - INFO [kytos.napps.kytos/topology] (MainThread) verify data in storehouse for interfaces.
2020-01-21 15:32:56,910 - INFO [kytos.napps.kytos/topology] (MainThread) verify data in storehouse for links.
2020-01-21 15:32:56,913 - INFO [kytos.napps] (topology) Running NApp: <Main(topology, started 139857368876800)>
2020-01-21 15:32:56,919 - INFO [kytos.core.api_server] (MainThread) Started /api/kytos/topology/v3/interfaces/<interface_id>/metadata - POST
2020-01-21 15:32:56,922 - INFO [kytos.core.api_server] (MainThread) Started /api/kytos/topology/v3/links/<link_id>/metadata - POST
2020-01-21 15:32:56,925 - INFO [kytos.core.api_server] (MainThread) Started /api/kytos/topology/v3/switches/<dpid>/metadata - POST
2020-01-21 15:32:56,930 - INFO [kytos.core.api_server] (MainThread) Started /api/kytos/topology/v3/interfaces/<interface_id>/metadata/<key> - DELETE
2020-01-21 15:32:56,934 - INFO [kytos.core.api_server] (MainThread) Started /api/kytos/topology/v3/links/<link_id>/metadata/<key> - DELETE
2020-01-21 15:32:56,938 - INFO [kytos.core.api_server] (MainThread) Started /api/kytos/topology/v3/switches/<dpid>/metadata/<key> - DELETE
2020-01-21 15:32:56,942 - INFO [kytos.core.api_server] (MainThread) Started /api/kytos/topology/v3/interfaces/<interface_id>/disable - POST
2020-01-21 15:32:56,945 - INFO [kytos.core.api_server] (MainThread) Started /api/kytos/topology/v3/links/<link_id>/disable - POST
2020-01-21 15:32:56,948 - INFO [kytos.core.api_server] (MainThread) Started /api/kytos/topology/v3/switches/<dpid>/disable - POST
2020-01-21 15:32:56,953 - INFO [kytos.core.api_server] (MainThread) Started /api/kytos/topology/v3/interfaces/<interface_id>/enable - POST
2020-01-21 15:32:56,956 - INFO [kytos.core.api_server] (MainThread) Started /api/kytos/topology/v3/links/<link_id>/enable - POST
2020-01-21 15:32:56,959 - INFO [kytos.core.api_server] (MainThread) Started /api/kytos/topology/v3/switches/<dpid>/enable - POST
2020-01-21 15:32:56,961 - INFO [kytos.core.api_server] (MainThread) Started /api/kytos/topology/v3/interfaces/<interface_id>/metadata - GET
2020-01-21 15:32:56,965 - INFO [kytos.core.api_server] (MainThread) Started /api/kytos/topology/v3/interfaces - GET
2020-01-21 15:32:56,967 - INFO [kytos.core.api_server] (MainThread) Started /api/kytos/topology/v3/links/<link_id>/metadata - GET
2020-01-21 15:32:56,969 - INFO [kytos.core.api_server] (MainThread) Started /api/kytos/topology/v3/links - GET
2020-01-21 15:32:56,971 - INFO [kytos.core.api_server] (MainThread) Started /api/kytos/topology/v3/switches/<dpid>/metadata - GET
2020-01-21 15:32:56,973 - INFO [kytos.core.api_server] (MainThread) Started /api/kytos/topology/v3/switches - GET
2020-01-21 15:32:56,975 - INFO [kytos.core.api_server] (MainThread) Started /api/kytos/topology/v3/ - GET
2020-01-21 15:32:56,975 - INFO [kytos.core.controller] (MainThread) Loading NApp kytos/pathfinder
2020-01-21 15:32:57,310 - INFO [kytos.napps] (pathfinder) Running NApp: <Main(pathfinder, started 139857368876800)>
2020-01-21 15:32:57,314 - INFO [kytos.core.api_server] (MainThread) Started /api/kytos/pathfinder/v2/ - POST
2020-01-21 15:32:57,314 - INFO [kytos.core.controller] (MainThread) Loading NApp kytos/mef_eline
2020-01-21 15:32:57,529 - INFO [apscheduler.scheduler] (MainThread) Scheduler started
2020-01-21 15:32:57,595 - INFO [kytos.napps.kytos/mef_eline] (MainThread) Create box from storehouse.
2020-01-21 15:32:57,601 - INFO [kytos.napps.kytos/mef_eline] (MainThread) Bootstraping storehouse box for kytos.mef_eline.circuits.
2020-01-21 15:32:57,603 - INFO [kytos.napps] (mef_eline) Running NApp: <Main(mef_eline, started 139857017632512)>
2020-01-21 15:32:57,607 - INFO [kytos.core.api_server] (MainThread) Started /api/kytos/mef_eline/v2/evc/ - POST
2020-01-21 15:32:57,610 - INFO [kytos.core.api_server] (MainThread) Started /api/kytos/mef_eline/v2/evc/<circuit_id> - GET
2020-01-21 15:32:57,611 - INFO [kytos.core.api_server] (MainThread) Started /api/kytos/mef_eline/v2/evc/ - GET
2020-01-21 15:32:57,613 - INFO [kytos.core.api_server] (MainThread) Started /api/kytos/mef_eline/v2/evc/<circuit_id> - PATCH
2020-01-21 15:32:57,639 - INFO [kytos.core.controller] (MainThread) Raw Event Handler started
2020-01-21 15:32:57,639 - INFO [kytos.core.controller] (MainThread) Message In Event Handler started
2020-01-21 15:32:57,639 - INFO [kytos.core.controller] (MainThread) Message Out Event Handler started
2020-01-21 15:32:57,640 - INFO [kytos.core.controller] (MainThread) App Event Handler started
2020-01-21 15:32:57,867 - INFO [kytos.napps.kytos/mef_eline] (Thread-14) Box 45096b807ff04ebc8952adf4b1485ef3 was created in kytos.mef_eline.circuits.
2020-01-21 15:32:57,914 - INFO [kytos.napps.kytos/mef_eline] (Thread-15) Retrieve box with 5ba74ad4c218485ea8b37471f61a260a from kytos.mef_eline.circuits.
2020-01-21 15:32:58,050 - INFO [kytos.napps.kytos/mef_eline] (Thread-19) Box 5ba74ad4c218485ea8b37471f61a260a was load from storehouse.
2020-01-21 15:32:58,075 - WARNING [werkzeug] (ThreadPoolExecutor-0_0) WebSocket transport not available. Install eventlet or gevent and gevent-websocket for improved performance.
```

 * Serving Flask app "kytos.core.controller" (lazy loading)
 * Environment: production

**An this is the messages I get after the console finished opening:**

```
kytos $> 2020-01-21 15:32:59,159 - INFO [kytos.core.atcp_server] (MainThread) New connection from 67.17.206.223:58612
Exception in thread Thread-28:
Traceback (most recent call last):
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/tmp/kytos/kytos/core/helpers.py", line 72, in threaded_handler
    handler(*args)
  File "/root/python3-jab/var/lib/kytos/napps/kytos/mef_eline/main.py", line 181, in trigger_evc_reprovisioning
    evc = self.evc_from_dict(data)
  File "/root/python3-jab/var/lib/kytos/napps/kytos/mef_eline/main.py", line 236, in evc_from_dict
    data[attribute] = self.link_from_dict(value)
  File "/root/python3-jab/var/lib/kytos/napps/kytos/mef_eline/main.py", line 264, in link_from_dict
    id_a = link_dict.get('endpoint_a')
AttributeError: 'list' object has no attribute 'get'
2020-01-21 15:32:59,187 - INFO [kytos.napps.kytos/of_core] (Thread-43) Connection ('67.17.206.223', 58612), Switch 00:00:6c:ec:5a:08:73:7f: OPENFLOW HANDSHAKE COMPLETE

Exception in thread Thread-51:
Traceback (most recent call last):
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/tmp/kytos/kytos/core/helpers.py", line 72, in threaded_handler
    handler(*args)
  File "/root/python3-jab/var/lib/kytos/napps/kytos/mef_eline/main.py", line 181, in trigger_evc_reprovisioning
    evc = self.evc_from_dict(data)
  File "/root/python3-jab/var/lib/kytos/napps/kytos/mef_eline/main.py", line 236, in evc_from_dict
    data[attribute] = self.link_from_dict(value)
  File "/root/python3-jab/var/lib/kytos/napps/kytos/mef_eline/main.py", line 264, in link_from_dict
    id_a = link_dict.get('endpoint_a')
AttributeError: 'list' object has no attribute 'get'
```

**Comment by josemauro** [comment]
Hey Daniela, can you give more information to reproduce this problem ? Like where did you get the new Kytos version (from pip or GitHub master)? Did you use  any commands after install it? Thanks. :)

**Comment by dgarc330** [comment]
Hey there, the only thing I did was installed kytos from scratch by cloning everything from the master branch.

**Comment by josemauro** [comment]
Hey Daniela, sorry for the late.  Are you still getting these problems? I tried to reproduce it and I did not get the same result as you, so let me know if I missed something, please. These were my exactly steps:

1- create folder 'mkdir testing_kytos_2019-2'
2- run 'cd testing_kytos_2019-2'
3- run 'python3 -m venv venv' (create a virtual environment)
4- run 'source venv/bin/activate' (activate venv)
5- run 'pip install --upgrade pip setuptools wheel'
6- run the bash script below to clone pyof, kytos-utils and kytos :

    for repo in python-openflow kytos-utils kytos; do
        git clone https://github.com/kytos/${repo}
    done

7- run the bash script below to install them:
    
    for repo in python-openflow kytos-utils kytos; do
        cd ${repo}
        python3 setup.py install
        cd ..
    done

8- run 'kytosd -f'
9- the output starting and finishing kytos:
```
kytosd -f               
2020-02-05 17:37:27,107 - INFO [kytos.core.logs] (MainThread) Logging config file "/home/jose/Desktop/testing_kytos_2019-2/venv/etc/kytos/logging.ini" loaded successfully.
2020-02-05 17:37:27,108 - INFO [kytos.core.controller] (MainThread) /home/jose/Desktop/testing_kytos_2019-2/venv/var/run/kytos
2020-02-05 17:37:27,108 - INFO [kytos.core.controller] (MainThread) Starting Kytos - Kytos Controller
2020-02-05 17:37:27,108 - INFO [kytos.core.controller] (MainThread) Starting TCP server: <kytos.core.atcp_server.KytosServer object at 0x7fcbe74aa2b0>
2020-02-05 17:37:27,108 - INFO [kytos.core.atcp_server] (MainThread) Kytos listening at 0.0.0.0:6653
2020-02-05 17:37:27,109 - INFO [kytos.core.controller] (MainThread) ThreadPool started: <concurrent.futures.thread.ThreadPoolExecutor object at 0x7fcbe7458e10>
2020-02-05 17:37:27,109 - INFO [kytos.core.controller] (MainThread) Loading Kytos NApps...
2020-02-05 17:37:27,110 - INFO [kytos.core.napps.napp_dir_listener] (MainThread) NAppDirListener Started...
2020-02-05 17:37:27,110 - WARNING [kytos.core.napps.manager] (MainThread) NApps dir (/home/jose/Desktop/testing_kytos_2019-2/venv/var/lib/kytos/napps/.installed) doesn't exist.
2020-02-05 17:37:27,112 - INFO [kytos.core.controller] (MainThread) Raw Event Handler started
2020-02-05 17:37:27,113 - INFO [kytos.core.controller] (MainThread) Message In Event Handler started
2020-02-05 17:37:27,113 - INFO [kytos.core.controller] (MainThread) Message Out Event Handler started
2020-02-05 17:37:27,113 - INFO [kytos.core.controller] (MainThread) App Event Handler started
2020-02-05 17:37:27,114 - WARNING [werkzeug] (ThreadPoolExecutor-0_0) WebSocket transport not available. Install eventlet or gevent and gevent-websocket for improved performance.
 * Serving Flask app "kytos.core.controller" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off

      _          _
     | |        | |
     | | ___   _| |_ ___  ___
     | |/ / | | | __/ _ \/ __|
     |   <| |_| | || (_) \__ \
     |_|\_\__,  |\__\___/|___/
            __/ |
           |___/
    
    Welcome to Kytos SDN Platform!

    We are making a huge effort to make sure that this console will work fine
    but for now it's still experimental.

    Kytos website.: https://kytos.io/
    Documentation.: https://docs.kytos.io/
    OF Address....: tcp://0.0.0.0:6653
    WEB UI........: http://0.0.0.0:8181/
    Kytos Version.: 2019.2

kytos $> quit                                                                                                                                            
Stopping Kytos daemon... Bye, see you!
2020-02-05 17:41:07,839 - INFO [kytos.core.controller] (MainThread) Stopping Kytos controller...
2020-02-05 17:41:07,839 - INFO [kytos.core.controller] (MainThread) Stopping Kytos
2020-02-05 17:41:07,839 - INFO [kytos.core.buffers] (MainThread) Stop signal received by Kytos buffers.
2020-02-05 17:41:07,839 - INFO [kytos.core.buffers] (MainThread) Sending KytosShutdownEvent to all apps.
2020-02-05 17:41:07,839 - INFO [kytos.core.buffers] (MainThread) [buffer: raw_event] Stop mode enabled. Rejecting new events.
2020-02-05 17:41:07,839 - INFO [kytos.core.buffers] (MainThread) [buffer: msg_in_event] Stop mode enabled. Rejecting new events.
2020-02-05 17:41:07,839 - INFO [kytos.core.buffers] (MainThread) [buffer: msg_out_event] Stop mode enabled. Rejecting new events.
2020-02-05 17:41:07,839 - INFO [kytos.core.buffers] (MainThread) [buffer: app_event] Stop mode enabled. Rejecting new events.
2020-02-05 17:41:07,862 - INFO [kytos.core.napps.napp_dir_listener] (MainThread) NAppDirListener Stopped...
2020-02-05 17:41:07,862 - INFO [kytos.core.controller] (MainThread) Stopping threadpool: <concurrent.futures.thread.ThreadPoolExecutor object at 0x7fcbe7458e10>
```

**Comment by dgarc330** [comment]
Thank you for your response @josemauro . Another one of our students here was the one who saw this error when working with pathfinder.

This happened after cloning the pathfinder repository from the master branch (they’re running the version from 2 commits ago) and executing the following command: python setup.py test

They also added the following code inside the test directory:

```
“”"Module to test Pathfinder”“”
from unittest import TestCase
from unittest.mock import Mock

from flask import request

from graph import KytosGraph
from main import Main

//from napps.kytos.topology import settings
from napps.kytos.topology.models import Topology


// Need to figure out an alternative
from kytos.core.switch import Switch
from kytos.core.interface import Interface
from kytos.core.link import Link

class TestPathfinder(TestCase):

    def restEmptyRequestTest(self):
        “”"Tests calling the rest API when request body is empty”“”
        result = None
        main = Main()
        main.setup()

        with test_request_context():
            result = main.get_path()

    @staticmethod
    def generateTopology():
        “”"Generates a predetermined topology”“”
        switches = {}
        interfaces = {}

        createSwitch(“S1",switches)
        addInterfaces(2, switches[“S1”], interfaces)

        createSwitch(“S2",switches)
        addInterfaces(3, switches[“S2”], interfaces)

        createSwitch(“S3",switches)
        addInterfaces(2, switches[“S2”], interfaces)

        links = {}

        links[“S1-L1<->S2-L1"] = Link(interfaces[“S1-L1”], interfaces[“S2-L1"])
        links[“S3-L1<->S2-L2”] = Link(interfaces[“S3-L1"], interfaces[“S2-L2”])
        links[“S1-L2<->S3-L2"] = Link(interfaces[“S1-L2”], interfaces[“S3-L2"])

        return Topology(switches,links)

    @staticmethod
    def createSwitch(name,switches):
        switches[name] = Switch(name)

    @staticmethod
    def addInterfaces(count,switch,interfaces):
        str0 = “{}-{}“.format(switch.dpid)
        for x in range(1,count):
            str1 = str0.format(x)
            iFace = Interface(str1,x,switch)
            interfaces[str1] = iFace
            switch.update_interface(iFace)
```

Any thoughts of what could be wrong? I tried to replicate it myself but no errors were found on my end.

**Comment by josemauro** [comment]
Well I'm little confused. I just saw your discussion with Humberto in Slack channel about the errors in pathfinder tests. Humberto recommended to use one specific \__init\__.py file (https://github.com/kytos/of_core/blob/master/tests/__init__.py)   to solve the problem.  Am I right? So, I thought that pathfinder problem it was different  from the problem described in this issue. I'm just trying to confirm that this 2 problems are same the one.

**Comment by dgarc330** [comment]
Sorry for the late reply @josemauro. This is another issue different for the one I've been discussing with Humberto. I came upon this errors after I updated to the latest kytos version, installed everything from scratch, and tried to start kytos. Those are the only steps I did and I cloned everything from the master branch.

**Comment by dgarc330** [comment]
Hello guys, I was going over our pending open issues and this one is very old and not happening anymore due to the fixes in the latest releases so I believe we can close it.
