### ISSUE TITLE
Remove hard dependency on github for UI

### ISSUE THREAD

**Issue by Ktmi** [kytos/kytos#1117]
# The Issue

In order to execute `kytosd`, the kytos needs to be able to download the UI from github. This download may be inaccessible, either from github being unavailable, firewall blocking github, or DNS unable to find github.

# Proposed Solution

- Allow for executing kytos without running the web server for the UI, while still running the web server for the api.
- Provide a different mechanism to couple the Web server for the UI to the controller.

**Comment by Ktmi** [comment]
Heres an error produced, when kytos can't access github due to DNS issues.
```
Traceback (most recent call last):
  File "/usr/lib/python3.6/urllib/request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/usr/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/usr/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/usr/lib/python3.6/http/client.py", line 1392, in connect
    super().connect()
  File "/usr/lib/python3.6/http/client.py", line 936, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/lib/python3.6/socket.py", line 704, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/lib/python3.6/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/kytosd", line 6, in <module>
    kytosd.main()
  File "/usr/local/lib/python3.6/dist-packages/kytos/core/kytosd.py", line 106, in main
    async_main(config)
  File "/usr/local/lib/python3.6/dist-packages/kytos/core/kytosd.py", line 137, in async_main
    controller = Controller(config)
  File "/usr/local/lib/python3.6/dist-packages/kytos/core/controller.py", line 122, in __init__
    self.napps_manager, self.options.napps)
  File "/usr/local/lib/python3.6/dist-packages/kytos/core/api_server.py", line 63, in __init__
    self.update_web_ui(force=False)
  File "/usr/local/lib/python3.6/dist-packages/kytos/core/api_server.py", line 225, in update_web_ui
    package = urlretrieve(uri)[0]
  File "/usr/lib/python3.6/urllib/request.py", line 248, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/usr/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 1361, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/usr/lib/python3.6/urllib/request.py", line 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno -3] Temporary failure in name resolution>

```
