### ISSUE TITLE
Kytos develop installation is broken with `setuptools==50`

### ISSUE THREAD

**Issue by gleybersonandrade** [kytos/kytos#1145]
An error is raised when trying to install kytos in develop mode using setuptools 50.0.0:

> /home/gleyberson/Dev/kytos-workspace/envs/test/lib/python3.6/site-packages/_distutils_hack/\__init\__.py:30: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
WARNING: The wheel package is not available.
Traceback (most recent call last):
  File "setup.py", line 273, in <module>
    'Environment :: No Input/Output (Daemon)',
  File "/home/gleyberson/Dev/kytos-workspace/envs/test/lib/python3.6/site-packages/setuptools/\__init\__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/home/gleyberson/Dev/kytos-workspace/envs/test/lib/python3.6/site-packages/setuptools/_distutils/core.py", line 134, in setup
    ok = dist.parse_command_line()
  File "/home/gleyberson/Dev/kytos-workspace/envs/test/lib/python3.6/site-packages/setuptools/_distutils/dist.py", line 484, in parse_command_line
    args = self._parse_command_opts(parser, args)
  File "/home/gleyberson/Dev/kytos-workspace/envs/test/lib/python3.6/site-packages/setuptools/dist.py", line 903, in _parse_command_opts
    nargs = _Distribution._parse_command_opts(self, parser, args)
  File "/home/gleyberson/Dev/kytos-workspace/envs/test/lib/python3.6/site-packages/setuptools/_distutils/dist.py", line 548, in _parse_command_opts
    "command class %s must subclass Command" % cmd_class)
distutils.errors.DistutilsClassError: command class <class 'setuptools.command.develop.develop'> must subclass Command

Some issues about this problem are opened in setuptools repo:

https://github.com/pypa/setuptools/issues/2366
https://github.com/pypa/setuptools/issues/2355

A possible temporary solution to this problem is to freeze the _setuptools_ version to 49.6.0.

**Comment by josemauro** [comment]
I read some discussions involving problems with 'setuptools'==50.0, some of them very recent, and I'm not sure if we are facing the same problem. Some of that discussions are suggesting problems between setuptools and pip. Anyway, I think that we should remove the use of 'distutils' in 'setup.py', it could be a good solution once 'setuptools' is replacing it.

**Comment by cmagnobarbosa** [comment]
This bug was resolved in the new version of setuptools 50.1, but they recommend made some changes :

source: https://github.com/pypa/setuptools/blob/master/CHANGES.rst

> #2350: Setuptools reverts using the included distutils by default. Platform maintainers and system integrators and others are strongly encouraged to set SETUPTOOLS_USE_DISTUTILS=local to help identify and work through the reported issues with distutils adoption, mainly to file issues and pull requests with pypa/distutils such that distutils performs as needed across every supported environment.
