### ISSUE TITLE
Intermittent RuntimeError when killing kytosd

### ISSUE THREAD

**Issue by rmotitsuki** [kytos/kytos#1235]
Killing kytosd process using command `pkill kytosd` throws a RuntimeError in log.
It is intermittent and happens with foreground and background kytos.
It is not critical to Kytos normal functioning, but it causes errors in end-to-end test that monitors kytos log files.

```
concurrent.futures:ERROR _base:326:  exception calling callback for <Future at 0x7f63c09897b8 state=finished returned NoneType>
Traceback (most recent call last):
File "/usr/lib/python3.6/concurrent/futures/_base.py", line 324, in _invoke_callbacks                               
  callback(self)
File "/usr/lib/python3.6/asyncio/futures.py", line 417, in _call_set_state  
  dest_loop.call_soon_threadsafe(_set_state, destination, source)                                        
File "/usr/lib/python3.6/asyncio/base_events.py", line 637, in call_soon_threadsafe           
  self._check_closed()                                                                                            
File "/usr/lib/python3.6/asyncio/base_events.py", line 377, in _check_closed
  raise RuntimeError('Event loop is closed')                                                               
```

**Comment by hdiogenes** [comment]
Fixed in #1238.
