### ISSUE TITLE
Connection Socket FD Exception

### ISSUE THREAD

**Issue by erickvermot** [kytos/kytos#344]
after initializing kytos, and running mininet:
$ sudo mn --arp --mac --controller=remote,ip=127.0.0.1 --switch=ovsk,protocols=OpenFlow10
kytosd raises an Exception apparently related to the connection socket not existing yet.
It looks like it  is running in some sort of concurrency between the creation of the socket by mininet, and the attempt to write to it by kytos.

```
    Exception in thread MsgOutEvent Handler:
    Traceback (most recent call last):
        File "/usr/lib/python3.6/site-packages/kytos/core/switch.py", line 229, id
        self.socket.send(buffer)
    OSError: [Errno 9] Bad file descriptor
```

**Comment by renanrodrigo** [comment]
I had the same output when quitting mininet.
I started mininet first, and then `kytosd- f`; when closing, got:
```
2017-04-18 09:31:22,256 - INFO [kytos.core.tcp_server] (Thread-4) Client 127.0.0.1:59350 disconnected. Reason: None
Exception in thread MsgOutEvent Handler:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/renan/trabalho/vvvvv/lib/python3.6/site-packages/kytos/core/controller.py", line 309, in msg_out_event_handler
    destination.send(message.pack())
  File "/home/renan/trabalho/vvvvv/lib/python3.6/site-packages/kytos/core/switch.py", line 228, in send
    self.socket.send(buffer)
OSError: [Errno 9] Bad file descriptor
```

**Comment by beraldoleal** [comment]
@erickvermot said that this was not solved.

**Comment by diraol** [comment]
Just a quick thought. Specially on @renanrodrigo 's case it may be a problem timing by having the TCPServer thread finished prior to the "tcp handler" thread.

About @erickvermot, this may be a problem related to "old opened sockets" from a prior instance of kytos or mininet. Sometime the python TCPServer glue itself on the 6633 port even after shutting down kytos. I have had this kind o problem on the past, and waiting some time for a "cleanup" may solve the problem.
[Another possible source of problems is mininet itself, always run `mn -c` prior to run mininet or start kytos.]

**Comment by erickvermot** [comment]
@diraol, I agree about the problem @renanrodrigo is facing.
And I agree about the existence of the second problem, which occurs because the socket remains in a WAIT state to ensure the destination socket receives the final AKN. But this problem occurs when we try to bind the address to the socket, not when we try to write to in. The new tcp server and handler proposed in PR https://github.com/kytos/kytos/pull/374 deals with this binding issue by retrying a few time to bind the socket.
[UPDATE] At the time, other members (@diraol, @cemsbr, @renanrodrigo) did not agree with the workaround of trying to rebind the socket when this occurs, so it was removed from #374. The issue still remains, even though it rarely occurs.
When it occurs when trying to close the socket, in PR #374 the exception is simply captured and ignored.
