### ISSUE TITLE
Problems in setup.py install

### ISSUE THREAD

**Issue by renanrodrigo** [kytos/kytos#391]
As the last changes were made, the line below repeats itself for a long time before kytos can be installed using setup.py install.

```
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
```

**Comment by renanrodrigo** [comment]
Inside the docker container, installing kytos is not possible.
```
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
pysass.cpp:2:20: fatal error: Python.h: No such file or directory
 #include <Python.h>
                    ^
compilation terminated.
Traceback (most recent call last):
  File "/usr/lib/python3.6/distutils/unixccompiler.py", line 118, in _compile
    extra_postargs)
  File "/usr/lib/python3.6/distutils/ccompiler.py", line 909, in spawn
    spawn(cmd, dry_run=self.dry_run)
  File "/usr/lib/python3.6/distutils/spawn.py", line 36, in spawn
    _spawn_posix(cmd, search_path, dry_run=dry_run)
  File "/usr/lib/python3.6/distutils/spawn.py", line 159, in _spawn_posix
    % (cmd, exit_status))
distutils.errors.DistutilsExecError: command 'x86_64-linux-gnu-gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python3.6/dist-packages/setuptools-34.3.3-py3.6.egg/setuptools/command/bdist_egg.py", line 161, in run
  File "/usr/local/lib/python3.6/dist-packages/setuptools-34.3.3-py3.6.egg/setuptools/command/bdist_egg.py", line 147, in call_command
  File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python3.6/dist-packages/setuptools-34.3.3-py3.6.egg/setuptools/command/install_lib.py", line 11, in run
  File "/usr/lib/python3.6/distutils/command/install_lib.py", line 109, in build
    self.run_command('build_ext')
  File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python3.6/dist-packages/setuptools-34.3.3-py3.6.egg/setuptools/command/build_ext.py", line 75, in run
  File "/usr/lib/python3.6/distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/usr/lib/python3.6/distutils/command/build_ext.py", line 448, in build_extensions
    self._build_extensions_serial()
  File "/usr/lib/python3.6/distutils/command/build_ext.py", line 473, in _build_extensions_serial
    self.build_extension(ext)
  File "/usr/local/lib/python3.6/dist-packages/setuptools-34.3.3-py3.6.egg/setuptools/command/build_ext.py", line 196, in build_extension
  File "/usr/lib/python3.6/distutils/command/build_ext.py", line 533, in build_extension
    depends=ext.depends)
  File "/usr/lib/python3.6/distutils/ccompiler.py", line 574, in compile
    self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
  File "/usr/lib/python3.6/distutils/unixccompiler.py", line 120, in _compile
    raise CompileError(msg)
distutils.errors.CompileError: command 'x86_64-linux-gnu-gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/setuptools-34.3.3-py3.6.egg/setuptools/sandbox.py", line 157, in save_modules
  File "/usr/local/lib/python3.6/dist-packages/setuptools-34.3.3-py3.6.egg/setuptools/sandbox.py", line 198, in setup_context
  File "/usr/local/lib/python3.6/dist-packages/setuptools-34.3.3-py3.6.egg/setuptools/sandbox.py", line 255, in run_setup
  File "/usr/local/lib/python3.6/dist-packages/setuptools-34.3.3-py3.6.egg/setuptools/sandbox.py", line 285, in run
  File "/usr/local/lib/python3.6/dist-packages/setuptools-34.3.3-py3.6.egg/setuptools/sandbox.py", line 253, in runner
  File "/usr/local/lib/python3.6/dist-packages/setuptools-34.3.3-py3.6.egg/setuptools/sandbox.py", line 47, in _execfile
  File "/tmp/easy_install-38owhqbk/libsass-0.12.3/setup.py", line 262, in <module>
    ])
  File "/usr/lib/python3.6/distutils/core.py", line 163, in setup
    raise SystemExit("error: " + str(msg))
SystemExit: error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/setuptools-34.3.3-py3.6.egg/setuptools/command/easy_install.py", line 1106, in run_setup
  File "/usr/local/lib/python3.6/dist-packages/setuptools-34.3.3-py3.6.egg/setuptools/sandbox.py", line 258, in run_setup
  File "/usr/lib/python3.6/contextlib.py", line 100, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.6/dist-packages/setuptools-34.3.3-py3.6.egg/setuptools/sandbox.py", line 198, in setup_context
  File "/usr/lib/python3.6/contextlib.py", line 100, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.6/dist-packages/setuptools-34.3.3-py3.6.egg/setuptools/sandbox.py", line 169, in save_modules
  File "/usr/local/lib/python3.6/dist-packages/setuptools-34.3.3-py3.6.egg/setuptools/sandbox.py", line 144, in resume
  File "/usr/local/lib/python3.6/dist-packages/six-1.10.0-py3.6.egg/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.6/dist-packages/setuptools-34.3.3-py3.6.egg/setuptools/sandbox.py", line 157, in save_modules
  File "/usr/local/lib/python3.6/dist-packages/setuptools-34.3.3-py3.6.egg/setuptools/sandbox.py", line 198, in setup_context
  File "/usr/local/lib/python3.6/dist-packages/setuptools-34.3.3-py3.6.egg/setuptools/sandbox.py", line 255, in run_setup
  File "/usr/local/lib/python3.6/dist-packages/setuptools-34.3.3-py3.6.egg/setuptools/sandbox.py", line 285, in run
  File "/usr/local/lib/python3.6/dist-packages/setuptools-34.3.3-py3.6.egg/setuptools/sandbox.py", line 253, in runner
  File "/usr/local/lib/python3.6/dist-packages/setuptools-34.3.3-py3.6.egg/setuptools/sandbox.py", line 47, in _execfile
  File "/tmp/easy_install-38owhqbk/libsass-0.12.3/setup.py", line 262, in <module>
    ])
  File "/usr/lib/python3.6/distutils/core.py", line 163, in setup
    raise SystemExit("error: " + str(msg))
SystemExit: error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 261, in <module>
    'Environment :: No Input/Output (Daemon)',
  File "/usr/lib/python3.6/distutils/core.py", line 108, in setup
    _setup_distribution = dist = klass(attrs)
  File "/usr/local/lib/python3.6/dist-packages/setuptools-34.3.3-py3.6.egg/setuptools/dist.py", line 318, in __init__
  File "/usr/local/lib/python3.6/dist-packages/setuptools-34.3.3-py3.6.egg/setuptools/dist.py", line 373, in fetch_build_eggs
  File "/usr/local/lib/python3.6/dist-packages/setuptools-34.3.3-py3.6.egg/pkg_resources/__init__.py", line 851, in resolve
  File "/usr/local/lib/python3.6/dist-packages/setuptools-34.3.3-py3.6.egg/pkg_resources/__init__.py", line 1123, in best_match
  File "/usr/local/lib/python3.6/dist-packages/setuptools-34.3.3-py3.6.egg/pkg_resources/__init__.py", line 1135, in obtain
  File "/usr/local/lib/python3.6/dist-packages/setuptools-34.3.3-py3.6.egg/setuptools/dist.py", line 441, in fetch_build_egg
  File "/usr/local/lib/python3.6/dist-packages/setuptools-34.3.3-py3.6.egg/setuptools/command/easy_install.py", line 674, in easy_install
  File "/usr/local/lib/python3.6/dist-packages/setuptools-34.3.3-py3.6.egg/setuptools/command/easy_install.py", line 700, in install_item
  File "/usr/local/lib/python3.6/dist-packages/setuptools-34.3.3-py3.6.egg/setuptools/command/easy_install.py", line 881, in install_eggs
  File "/usr/local/lib/python3.6/dist-packages/setuptools-34.3.3-py3.6.egg/setuptools/command/easy_install.py", line 1120, in build_and_install
  File "/usr/local/lib/python3.6/dist-packages/setuptools-34.3.3-py3.6.egg/setuptools/command/easy_install.py", line 1108, in run_setup
distutils.errors.DistutilsError: Setup script exited with error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
```

**Comment by diraol** [comment]
me and @cemsbr are investigating this issue.

**Comment by beraldoleal** [comment]
@diraol @cemsbr any update on this ?

**Comment by diraol** [comment]
I think this error reported by @renanrodrigo is fixed (by kytos/kytos#392). But I'm doing a bunch of tests here to see if I can reproduce it or any other errors are found.

**Comment by beraldoleal** [comment]
@renanrodrigo please, confirm if you still have this problem.

**Comment by renanrodrigo** [comment]
This error does not appear anymore.

**Comment by beraldoleal** [comment]
Thanks. I will close for now, if we have this problem again, let reopen.
