### ISSUE TITLE
Error related to config paths

### ISSUE THREAD

**Issue by erickvermot** [kytos/kytos#399]
kytos.conf.template uses the syntax ``{{prefix}}`` + path, as in ``{{prefix}}/etc/kytos/logging.ini``, with ``prefix`` being the ``virtual_env`` path or the root dir ``/``, making the paths start with a double slash ``//`` instead of a single one. It is harmless most of the time, but not always...

```
# kytosd -f
Traceback (most recent call last):
  File "/usr/lib/python3.6/logging/handlers.py", line 835, in _connect_unixsocket
    self.socket.connect(address)
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/sbin/kytosd", line 4, in <module>
    __import__('pkg_resources').run_script('kytos==2017.1b1', 'kytosd')
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 738, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1499, in run_script
    exec(code, namespace, namespace)
  File "/usr/lib/python3.6/site-packages/kytos-2017.1b1-py3.6.egg/EGG-INFO/scripts/kytosd", line 58, in <module>
    controller.start()
  File "/usr/lib/python3.6/site-packages/kytos-2017.1b1-py3.6.egg/kytos/core/controller.py", line 120, in start
    self.enable_logs()
  File "/usr/lib/python3.6/site-packages/kytos-2017.1b1-py3.6.egg/kytos/core/controller.py", line 115, in enable_logs
    LogManager.load_logging_file(self.options.logging)
  File "/usr/lib/python3.6/site-packages/kytos-2017.1b1-py3.6.egg/kytos/core/logs.py", line 25, in load_logging_file
    config.fileConfig(logging_file)
  File "/usr/lib/python3.6/logging/config.py", line 84, in fileConfig
    handlers = _install_handlers(cp, formatters)
  File "/usr/lib/python3.6/logging/config.py", line 148, in _install_handlers
    h = klass(*args)
  File "/usr/lib/python3.6/logging/handlers.py", line 818, in __init__
    self._connect_unixsocket(address)
  File "/usr/lib/python3.6/logging/handlers.py", line 846, in _connect_unixsocket
    self.socket.connect(address)
FileNotFoundError: [Errno 2] No such file or directory
```

logging_file contains ``//etc/kytos/logging.ini``.

**Comment by erickvermot** [comment]
proposed fix:
https://github.com/kytos/kytos/compare/master...erickvermot:v_env_prefix_fix

should I make a PR?

**Comment by beraldoleal** [comment]
@erickvermot this is a "ok" PR. Except by the second part. I need a review from @diraol, @macartur or someone that was working on this.

I can accept it without problems. But I think that your patch is not related to this "No such file or directory" error, because Unix can handle double slashes.

**Comment by erickvermot** [comment]
yes @beraldoleal, I confirm the error is actually related to not having syslog-ng running.
