### ISSUE TITLE
kytosd needs syslog up and running

### ISSUE THREAD

**Issue by erickvermot** [kytos/kytos#400]
If syslog is not running, kytosd fails...

**Comment by beraldoleal** [comment]
Error details:
```
root@2866a7de88ee:/# kytosd -f
Traceback (most recent call last):
  File "/usr/lib/python3.6/logging/handlers.py", line 835, in _connect_unixsocket
    self.socket.connect(address)
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/kytosd", line 58, in <module>
    controller.start()
  File "/usr/local/lib/python3.6/dist-packages/kytos/core/controller.py", line 120, in start
    self.enable_logs()
  File "/usr/local/lib/python3.6/dist-packages/kytos/core/controller.py", line 115, in enable_logs
    LogManager.load_logging_file(self.options.logging)
  File "/usr/local/lib/python3.6/dist-packages/kytos/core/logs.py", line 24, in load_logging_file
    config.fileConfig(logging_file)
  File "/usr/lib/python3.6/logging/config.py", line 84, in fileConfig
    handlers = _install_handlers(cp, formatters)
  File "/usr/lib/python3.6/logging/config.py", line 148, in _install_handlers
    h = klass(*args)
  File "/usr/lib/python3.6/logging/handlers.py", line 818, in __init__
    self._connect_unixsocket(address)
  File "/usr/lib/python3.6/logging/handlers.py", line 846, in _connect_unixsocket
    self.socket.connect(address)
FileNotFoundError: [Errno 2] No such file or directory
```

We should be able to capture this error and continue without syslog, only displaying a warning.

**Comment by cemsbr** [comment]
This solution requires an exception that the docker instance does not raise. I added busybox-syslogd to the image as a workaround.

**Comment by diraol** [comment]
@cemsbr this is solved? Can we close this issue?

**Comment by cemsbr** [comment]
@diraol, not yet. I reopened it after we debugged it together (remember the exception that Python doesn't raise?).

**Comment by cemsbr** [comment]
Kytos can't directly run on MacOS because of this issue.
