### ISSUE TITLE
Connection raise 'AttributeError' trying to close a socket

### ISSUE THREAD

**Issue by macartur** [kytos/kytos#466]
```
Exception in thread Thread-26:
Traceback (most recent call last):
  File "/var/lib/kytos/napps/kytos/of_core/main.py", line 137, in handle_raw_in
    message = GenericHello(packet=packet)
  File "/var/lib/kytos/napps/../napps/kytos/of_core/utils.py", line 126, in __init__
    self.unpack(packet)
  File "/var/lib/kytos/napps/../napps/kytos/of_core/utils.py", line 163, in unpack
    raise UnpackException
pyof.foundation.exceptions.UnpackException

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/dist-packages/kytos-2017.1b3-py3.6.egg/kytos/core/helpers.py", line 68, in threaded_handler
    handler(*args)
  File "/var/lib/kytos/napps/kytos/of_core/main.py", line 147, in handle_raw_in
    connection.close()
  File "/usr/local/lib/python3.6/dist-packages/kytos-2017.1b3-py3.6.egg/kytos/core/connection.py", line 95, in close
    self.socket.close()
AttributeError: 'NoneType' object has no attribute 'close'
```

**Comment by erickvermot** [comment]
Although this rarely occurs, this problem has been there for a while (since the creation of the Connection class almost a year ago...), but has been made 'less rare' since the inclusion of the debug message and the shutdown method.
I had solved this but forgot to include the commit when I made the PR... sorry.
It happens because the socket happened to be closed between line 91 where we check if the socket still exists and lines 94 to 96 where we use the 'socket' attribute. So checking for the existence of the socket is not a good way to proceed, and catching the Exception is the way to go. (and if we catch the exception we do not need to check for the attribute in line 91 anymore, see comment in the PR).

I am commenting this because this problem exposes a more general one, that need to be fixed in other parts of the code:
- Checking for an attribute that may not exist anymore before using it is not enough when concurrent methods may affect it. We need to try to use and catch the AttributeError exceptions in all these cases.
Should I make a general issue for this @beraldoleal?
