### ISSUE TITLE
UnboundLocalError: local variable 'debug_msg' referenced before assignment

### ISSUE THREAD

**Issue by jab1982** [kytos/kytos#488]
After another error received (that I will submit later), I seeing this msg:

During handling of the above exception, another exception occurred:
```bash
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/jab/kytos/kytos/kytos/core/helpers.py", line 68, in threaded_handler
    handler(*args)
  File "/home/jab/python36/var/lib/kytos/napps/kytos/of_core/main.py", line 158, in handle_raw_in
    connection.id, debug_msg)
UnboundLocalError: local variable 'debug_msg' referenced before assignment
```
My suggestion : move log.debug to be inside of "if type(e) == AttributeError:"
```bash
$ git diff
diff --git a/napps/kytos/of_core/main.py b/napps/kytos/of_core/main.py
index 56eaca5..6ef4816 100644
--- a/napps/kytos/of_core/main.py
+++ b/napps/kytos/of_core/main.py
@@ -154,8 +154,8 @@ class Main(KytosNApp):
                 log.debug(e)
                 if type(e) == AttributeError:
                     debug_msg = 'connection closed before version negotiation'
-                log.debug('Connection %s: %s',
-                          connection.id, debug_msg)
+                    log.debug('Connection %s: %s',
+                              connection.id, debug_msg)
                 connection.close()
                 return
```

**Comment by beraldoleal** [comment]
@jab1982 thanks.. yes.. probably an indentation error. @macartur can you please submit a PR ?
