### ISSUE TITLE
[controller.py] AppEventHandler RuntimeError: dictionary changed size during iteration

### ISSUE THREAD

**Issue by viniarck** [kytos/kytos#558]
Guys, I just came across this race condition. I was prototyping my NApp viniciusarcanjo/kyslacker, which basically listens to other NApps events, and I noticed this traceback that is happening sometimes. It looks like the self.events_listeners in controller.py is changing its size because of this race condition. 

After applying this patch I don't see this issue anymore. Basically, I copied the dict to avoid the race condition in the first place:

```
diff --git a/kytos/core/controller.py b/kytos/core/controller.py
index ecde384..7509bfd 100644
--- a/kytos/core/controller.py
+++ b/kytos/core/controller.py
@@ -331,7 +331,8 @@ class Controller(object):
         Args:
             event (~kytos.core.KytosEvent): An instance of a KytosEvent.
         """
-        for event_regex, listeners in self.events_listeners.items():
+        events_listeners = dict(self.events_listeners).items()
+        for event_regex, listeners in events_listeners:
             # Do not match if the event has more characters
             # e.g. "shutdown" won't match "shutdown.kytos/of_core"
             if event_regex[-1] != '$' or event_regex[-2] == '\\':
```

> An example when this race condition occurred:

```
? kytosd -f
2017-09-02 14:49:52,379 - INFO [kytos.core.logs] (MainThread) Logging config file "/home/arcanjo/repos/kytos/.direnv/python-3.6.1/etc/kytos/logging.ini" loaded successfully.
2017-09-02 14:49:52,379 - INFO [kytos.core.controller] (MainThread) /home/arcanjo/repos/kytos/.direnv/python-3.6.1/var/run/kytos
2017-09-02 14:49:52,379 - INFO [kytos.core.controller] (MainThread) Starting Kytos - Kytos Controller
2017-09-02 14:49:52,380 - WARNING [werkzeug] (API server) WebSocket transport not available. Install eventlet or gevent and gevent-websocket for improved performance.
2017-09-02 14:49:52,380 - INFO [kytos.core.controller] (RawEvent Handler) Raw Event Handler started
2017-09-02 14:49:52,380 - INFO [kytos.core.tcp_server] (TCP server) Kytos listening at 0.0.0.0:6633
2017-09-02 14:49:52,380 - INFO [kytos.core.controller] (MsgInEvent Handler) Message In Event Handler started
2017-09-02 14:49:52,381 - INFO [kytos.core.controller] (MsgOutEvent Handler) Message Out Event Handler started
2017-09-02 14:49:52,381 - INFO [kytos.core.controller] (AppEvent Handler) App Event Handler started
2017-09-02 14:49:52,381 - INFO [kytos.core.controller] (MainThread) Loading Kytos NApps...
2017-09-02 14:49:52,384 - INFO [kytos.core.napps.napp_dir_listener] (MainThread) NAppDirListener Started...
2017-09-02 14:49:52,385 - INFO [kytos.core.controller] (MainThread) Loading NApp viniciusarcanjo/kyslacker
2017-09-02 14:49:52,414 - INFO [kytos.core.controller] (MainThread) Loading NApp viniciusarcanjo/kyslacker-client
2017-09-02 14:49:52,415 - DEBUG [kytos.core.buffers] (MainThread) [buffer: app_event] Added: viniciusarcanjo/kyslacker.send
2017-09-02 14:49:52,415 - DEBUG [kytos.core.buffers] (AppEvent Handler) [buffer: app_event] Removed: viniciusarcanjo/kyslacker.send
2017-09-02 14:49:52,416 - INFO [kytos.core.controller] (MainThread) Loading NApp kytos/of_stats
Exception in thread AppEvent Handler:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/arcanjo/repos/kytos/kytos/core/controller.py", line 421, in app_event_handler
    self.notify_listeners(event)
  File "/home/arcanjo/repos/kytos/kytos/core/controller.py", line 334, in notify_listeners
    for event_regex, listeners in self.events_listeners.items():
RuntimeError: dictionary changed size during iteration

2017-09-02 14:49:52,458 - INFO [kytos.core.controller] (MainThread) Loading NApp kytos/of_core
```

> Another example where the race condition didn't occur:

```
? kytosd -f
2017-09-02 14:49:47,997 - INFO [kytos.core.logs] (MainThread) Logging config file "/home/arcanjo/repos/kytos/.direnv/python-3.6.1/etc/kytos/logging.ini" loaded successfully.
2017-09-02 14:49:47,997 - INFO [kytos.core.controller] (MainThread) /home/arcanjo/repos/kytos/.direnv/python-3.6.1/var/run/kytos
2017-09-02 14:49:47,998 - INFO [kytos.core.controller] (MainThread) Starting Kytos - Kytos Controller
2017-09-02 14:49:47,999 - WARNING [werkzeug] (API server) WebSocket transport not available. Install eventlet or gevent and gevent-websocket for improved performance.
2017-09-02 14:49:47,999 - INFO [kytos.core.tcp_server] (TCP server) Kytos listening at 0.0.0.0:6633
2017-09-02 14:49:47,999 - INFO [kytos.core.controller] (RawEvent Handler) Raw Event Handler started
2017-09-02 14:49:48,000 - INFO [kytos.core.controller] (MsgInEvent Handler) Message In Event Handler started
2017-09-02 14:49:48,000 - INFO [kytos.core.controller] (MsgOutEvent Handler) Message Out Event Handler started
2017-09-02 14:49:48,000 - INFO [kytos.core.controller] (AppEvent Handler) App Event Handler started
2017-09-02 14:49:48,000 - INFO [kytos.core.controller] (MainThread) Loading Kytos NApps...
2017-09-02 14:49:48,003 - INFO [kytos.core.napps.napp_dir_listener] (MainThread) NAppDirListener Started...
2017-09-02 14:49:48,004 - INFO [kytos.core.controller] (MainThread) Loading NApp viniciusarcanjo/kyslacker
2017-09-02 14:49:48,034 - INFO [kytos.core.controller] (MainThread) Loading NApp viniciusarcanjo/kyslacker-client
2017-09-02 14:49:48,035 - DEBUG [kytos.core.buffers] (MainThread) [buffer: app_event] Added: viniciusarcanjo/kyslacker.send
2017-09-02 14:49:48,035 - DEBUG [kytos.core.buffers] (AppEvent Handler) [buffer: app_event] Removed: viniciusarcanjo/kyslacker.send
2017-09-02 14:49:48,036 - INFO [kytos.core.controller] (MainThread) Loading NApp kytos/of_stats
2017-09-02 14:49:48,038 - DEBUG [kytos.core.controller] (AppEvent Handler) AppEvent handler called
2017-09-02 14:49:48,086 - INFO [kytos.core.controller] (MainThread) asdfLoading NApp kytos/of_core
2017-09-02 14:49:48,187 - INFO [root] (kyslacker) Running NApp: <Main(kyslacker, started 140098402248448)>
2017-09-02 14:49:48,188 - INFO [viniciusarcanjo/kyslacker] (Thread-6) msg: viniciusarcanjo/kyslacker-client INFO A new circuit X was provisioned for customer A
2017-09-02 14:49:48,189 - INFO [root] (kyslacker-client) Running NApasdfp: <Main(kyslacker-client, started 140098393855744)>
2017-09-02 14:49:48,195 - INFO [root] (of_stats) Running NApp: <Main(of_stats, started 140098005735168)>
2017-09-02 14:49:48,219 - INFO [root] (kytos/of_core) Running NApp: <Main(kytos/of_core, started 140098393855744)>

  _          _
 | |        | |
 | | ___   _| |_ ___  ___
 | |/ / | | | __/ _ \/ __|
 |   <| |_| | || (_) \__ \
 |_|\_\\__, |\__\___/|___/
        __/ |
       |___/

Welcome to Kytos SDN Platform!
```

**Comment by viniarck** [comment]
sha1:

*   26f395a (HEAD -> dev, upstream/master, upstream/HEAD, master) Merge pull request #557 from diraol/docs-pyenv
|\
| * 455bdc7 [doc] Adding pyenv on hacking
|/

**Comment by diraol** [comment]
Hi @viniciusarcanjo,

you are right, the way we coded this method does leave space for the given problem.

Can you send us a PullRequest with you proposed solution?
I would just change one thing. Instead of creating a new object and then using it on the for loop, I think you may just create it directly on the for loop `for ... in dict(...).items():`.
I think it may work.

Thanks for the contribution! =)

**Comment by beraldoleal** [comment]
@viniciusarcanjo can you confirm that your PR fixed this ? So we can close ?

**Comment by hdiogenes** [comment]
@viniarck, I've assigned this to you so we can close it.

Also, improving on the last comment, `d.copy()` is more concise and achieves the same result:

```
>>> d == d.copy()
True
>>> d is d.copy()
False
```

**Comment by viniarck** [comment]
Hi @hdiogenes. Yes, it's been solved. I'll close this issue.
