### ISSUE TITLE
"pip install -e .[dev]" exception

### ISSUE THREAD

**Issue by cemsbr** [kytos/kytos#585]

**Comment by cemsbr** [comment]
@renanrodrigo, I cannot reproduce the problem. What's the output you have?

**Comment by renanrodrigo** [comment]
Using Debian 9, in a fresh venv, I always get:
```
Exception:
Traceback (most recent call last):
  File "/root/teste/lib/python3.6/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/root/teste/lib/python3.6/site-packages/pip/commands/install.py", line 353, in run
    wb.build(autobuilding=True)
  File "/root/teste/lib/python3.6/site-packages/pip/wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "/root/teste/lib/python3.6/site-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/root/teste/lib/python3.6/site-packages/pip/req/req_set.py", line 666, in _prepare_file
    check_dist_requires_python(dist)
  File "/root/teste/lib/python3.6/site-packages/pip/utils/packaging.py", line 48, in check_dist_requires_python
    feed_parser.feed(metadata)
  File "/usr/lib/python3.6/email/feedparser.py", line 175, in feed
    self._input.push(data)
  File "/usr/lib/python3.6/email/feedparser.py", line 103, in push
    self._partial.write(data)
TypeError: string argument expected, got 'NoneType'

```
