### ISSUE TITLE
Topology update through event sometimes triggers an exception

### ISSUE THREAD

**Issue by hdiogenes** [kytos/kytos#720]
When that happens, the server must be restarted.

```Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/antonio/new_kytos/lib/python3.6/site-packages/kytos-2018.1b2-py3.6.egg/kytos/core/helpers.py", line 71, in threaded_handler
    handler(*args)
  File "/home/antonio/new_kytos/var/lib/kytos/napps/kytos/topology/main.py", line 373, in add_links
    interface_a.update_link(link)
AttributeError: 'NoneType' object has no attribute 'update_link'

Exception in thread Thread-109:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/antonio/new_kytos/lib/python3.6/site-packages/kytos-2018.1b2-py3.6.egg/kytos/core/helpers.py", line 71, in threaded_handler
    handler(*args)
  File "/home/antonio/new_kytos/var/lib/kytos/napps/amlight/coloring/main.py", line 51, in topology_updated
    [l.as_dict() for l in topology.links.values()]
  File "/home/antonio/new_kytos/var/lib/kytos/napps/amlight/coloring/main.py", line 51, in <listcomp>
    [l.as_dict() for l in topology.links.values()]
  File "/home/antonio/new_kytos/lib/python3.6/site-packages/kytos-2018.1b2-py3.6.egg/kytos/core/link.py", line 89, in as_dict
    'endpoint_a': self.endpoint_a.as_dict(),
AttributeError: 'NoneType' object has no attribute 'as_dict'```

**Comment by beraldoleal** [comment]
@macartur please can you see at least how to handle the `topology` exception ?

**Comment by hdiogenes** [comment]
To try to reproduce it, first install https://napps.kytos.io/amlight/coloring:

    kytos napps install amlight/coloring

**Comment by beraldoleal** [comment]
@viniciusarcanjo can you please help @llgoncalves to reproduce this? Looks like amlight/coloring napp is trying to import an deprecated code.

Which coloring version it was used during this exception. Can you please describe with more details this ?

**Comment by viniarck** [comment]
Sure. I'll take a look, and I'll talk to @llgoncalves

**Comment by viniarck** [comment]
The `amlight/coloring` NApp on napps.kytos.io is an old version, there are a few deprecated dependencies (`of_topology` and `of_flow_manager`):

```
❯ kytos napps install amlight/coloring
INFO    NApp amlight/coloring:
INFO      Searching local NApp...
INFO      Not found. Downloading from NApps Server...
INFO      Downloaded and installed.
INFO      Enabling...
INFO      Enabled.
INFO  Installing Dependencies:
INFO    NApp kytos/of_flow_manager:
INFO      Searching local NApp...
INFO      Not found. Downloading from NApps Server...
ERROR     NApp not found.
INFO      Enabling...
ERROR   Install NApp kytos/of_flow_manager first.
INFO    NApp kytos/of_lldp:
WARNING   Napp already enabled.
INFO    NApp kytos/of_topology:
INFO      Searching local NApp...
INFO      Not found. Downloading from NApps Server...
ERROR     NApp not found.
INFO      Enabling...
ERROR   Install NApp kytos/of_topology first.
```

I'll see if I can reproduce the problem wiith the latest version that the AmLight team is working on.

**Comment by hdiogenes** [comment]
I think the question here boils down to: what should [topology.add_links](https://github.com/kytos/topology/blob/master/main.py#L380) do when it receives `None` values for interfaces? Do we just set `interface_a` to `None`, or should we raise an error?

**Comment by beraldoleal** [comment]
A link MUST HAVE two interfaces, so if is none, we should raise an exception.

**Comment by beraldoleal** [comment]
This must be moved to kytos/topology repo.
