### ISSUE TITLE
Socket read error on new connection - openvswitch 2.5.2

### ISSUE THREAD

**Issue by hdiogenes** [kytos/kytos#724]
Sometimes a new connection is triggering a socket read error. The error is not as critical as it seems in the log, because right after that the connection is successfully established, but we have to investigate what is causing this message in the logs.

```
2018-04-24 15:56:52,893 - INFO [atcp_server] (MainThread) Connection lost with client 192.168.0.200:48628. Reason: None
2018-04-24 15:57:11,824 - INFO [atcp_server] (MainThread) New connection from 192.168.0.200:48630
2018-04-24 15:57:11,829 - INFO [atcp_server] (MainThread) Connection lost with client 192.168.0.200:48630. Reason: None
2018-04-24 15:57:11,829 - INFO [controller] (ThreadPoolExecutor-0_0) Handling kytos/core.connection.new...
2018-04-24 15:57:11,956 - INFO [atcp_server] (MainThread) New connection from 192.168.0.200:48632
2018-04-24 15:57:11,964 - INFO [controller] (ThreadPoolExecutor-0_0) Handling kytos/core.connection.new...
2018-04-24 15:57:11,988 - ERROR [asyncio] (MainThread) Fatal read error on socket transport
protocol: <kytos.core.atcp_server.KytosServerProtocol object at 0x106c9c080>
transport: <_SelectorSocketTransport fd=23 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/local/python3.6-dbg/lib/python3.6/asyncio/selector_events.py", line 723, in _read_ready
    data = self._sock.recv(self.max_size)
OSError: [Errno 9] Bad file descriptor
2018-04-24 15:57:11,994 - INFO [atcp_server] (MainThread) Connection lost with client 192.168.0.200:48632. Reason: [Errno 9] Bad file descriptor
2018-04-24 15:57:12,206 - INFO [atcp_server] (MainThread) New connection from 192.168.0.200:48634
2018-04-24 15:57:12,212 - INFO [controller] (ThreadPoolExecutor-0_0) Handling kytos/core.connection.new...
2018-04-24 15:57:12,286 - INFO [kytos/of_core] (Thread-4641) Connection ('192.168.0.200', 48634), Switch 00:00:00:00:00:00:00:01: OPENFLOW HANDSHAKE COMPLETE
```

**Comment by viniarck** [comment]
I just found a way to reproduce this issue when I was working on mef_eline:

1 - These napps are installed/loaded:

```
❯ kytos napps list

Status |         NApp ID          |             Description
=======+==========================+====================================
 [ie]  | kytos/flow_manager:2.1.0 | Manage switches' flows through a...
 [ie]  | kytos/mef_eline:2.1.0    | NApp to provision circuits from ...
 [ie]  | kytos/of_core:1.2.0      | OpenFlow Core of Kytos Controlle...
 [ie]  | kytos/of_lldp:0.1.1      | Discover network-to-network inte...
 [ie]  | kytos/of_stats:1.0.0     | Provide statistics of openflow s...
 [ie]  | kytos/pathfinder:2.1.0   | Keeps track of topology changes,...
 [ie]  | kytos/status:1.0.0       | Provides basic information about...
 [ie]  | kytos/topology:3.1.0     | Manage the network topology.
```

2 - I was running some tests with mef_eline:

3 - I had this evc.json payload:

```
{
  "name": "s2-s3",
  "uni_a": {
    "interface_id": "00:00:00:00:00:00:00:03:1",
    "tag": {
      "tag_type": 1,
      "value": 80
    }
  },
  "uni_z": {
    "interface_id": "00:00:00:00:00:00:00:02:1",
    "tag": {
      "tag_type": 1,
      "value": 80
    }
  }
}

```

4 - Making the request:

```
curl -X POST --data-binary @evc.json -H "Content-type: application/json" http://localhost:8181/api/kytos/mef_eline/v2/evc/ -v
```

5 - Whenever I make the request mentioned on step 4 I can see the error.

```
tos $> 2018-05-09 09:44:37,356 - ERROR [asyncio] (MainThread) Fatal read error on socket transport
protocol: <kytos.core.atcp_server.KytosServerProtocol object at 0x7f04f6d69160>
transport: <_SelectorSocketTransport fd=14 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib64/python3.6/asyncio/selector_events.py", line 723, in _read_ready
    data = self._sock.recv(self.max_size)
OSError: [Errno 9] Bad file descriptor
2018-05-09 09:44:37,357 - INFO [kytos/mef_eline] (mef_eline) The circuit d1ac664ff88947869882e9d59d93922f was deployed.
2018-05-09 09:44:37,358 - INFO [atcp_server] (MainThread) Connection lost with client 172.16.255.2:57226. Reason: [Errno 9] Bad file descriptor
2018-05-09 09:44:37,762 - INFO [atcp_server] (MainThread) New connection from 172.16.255.2:57450
```

**Comment by viniarck** [comment]
As a result the connection was flapping after each request:

```
kytos $> 2018-05-09 09:44:37,356 - ERROR [asyncio] (MainThread) Fatal read error on socket transport
protocol: <kytos.core.atcp_server.KytosServerProtocol object at 0x7f04f6d69160>
transport: <_SelectorSocketTransport fd=14 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib64/python3.6/asyncio/selector_events.py", line 723, in _read_ready
    data = self._sock.recv(self.max_size)
OSError: [Errno 9] Bad file descriptor
2018-05-09 09:44:37,357 - INFO [kytos/mef_eline] (mef_eline) The circuit d1ac664ff88947869882e9d59d93922f was deployed.
2018-05-09 09:44:37,358 - INFO [atcp_server] (MainThread) Connection lost with client 172.16.255.2:57226. Reason: [Errno 9] Bad file descriptor
2018-05-09 09:44:37,762 - INFO [atcp_server] (MainThread) New connection from 172.16.255.2:57450
2018-05-09 09:44:37,763 - INFO [atcp_server] (MainThread) New connection from 172.16.255.2:57452
2018-05-09 09:44:37,763 - INFO [controller] (ThreadPoolExecutor-0_0) Handling kytos/core.connection.new...
2018-05-09 09:44:37,764 - INFO [controller] (ThreadPoolExecutor-0_0) Handling kytos/core.connection.new...
2018-05-09 09:44:37,775 - INFO [kytos/of_core] (Thread-10964) Connection ('172.16.255.2', 57450), Switch 00:00:00:00:00:00:00:03: OPENFLOW HANDSHAKE COMPLETE
2018-05-09 09:44:39,763 - INFO [atcp_server] (MainThread) New connection from 172.16.255.2:57454
2018-05-09 09:44:39,764 - INFO [controller] (ThreadPoolExecutor-0_0) Handling kytos/core.connection.new...
2018-05-09 09:44:39,775 - INFO [kytos/of_core] (Thread-11008) Connection ('172.16.255.2', 57454), Switch 00:00:00:00:00:00:00:02: OPENFLOW HANDSHAKE COMPLETE
2018-05-09 09:46:25,460 - ERROR [asyncio] (MainThread) Fatal read error on socket transport
protocol: <kytos.core.atcp_server.KytosServerProtocol object at 0x7f04f6d69160>
transport: <_SelectorSocketTransport fd=14 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib64/python3.6/asyncio/selector_events.py", line 723, in _read_ready
    data = self._sock.recv(self.max_size)
OSError: [Errno 9] Bad file descriptor
2018-05-09 09:46:25,461 - INFO [atcp_server] (MainThread) Connection lost with client 172.16.255.2:57450. Reason: [Errno 9] Bad file descriptor
2018-05-09 09:46:25,461 - INFO [kytos/mef_eline] (mef_eline) The circuit 3f2a2c9e4599497aa06dffea34b369eb was deployed.
2018-05-09 09:46:25,465 - INFO [atcp_server] (MainThread) Connection lost with client 172.16.255.2:57454. Reason: None
2018-05-09 09:46:25,762 - INFO [atcp_server] (MainThread) New connection from 172.16.255.2:57492
2018-05-09 09:46:25,763 - INFO [atcp_server] (MainThread) New connection from 172.16.255.2:57494
2018-05-09 09:46:25,764 - INFO [controller] (ThreadPoolExecutor-0_0) Handling kytos/core.connection.new...
2018-05-09 09:46:25,764 - INFO [controller] (ThreadPoolExecutor-0_0) Handling kytos/core.connection.new...
2018-05-09 09:46:25,780 - INFO [kytos/of_core] (Thread-12472) Connection ('172.16.255.2', 57494), Switch 00:00:00:00:00:00:00:02: OPENFLOW HANDSHAKE COMPLETE
2018-05-09 09:46:25,797 - INFO [kytos/of_core] (Thread-12477) Connection ('172.16.255.2', 57492), Switch 00:00:00:00:00:00:00:03: OPENFLOW HANDSHAKE COMPLETE
C
```

**Comment by hdiogenes** [comment]
Thanks for the detailed information, @viniciusarcanjo, but I couldn't reproduce it here (using the same commands, napps, etc.). Can you post which mininet command you were running at the time?

**Comment by viniarck** [comment]
Hi @hdiogenes, I'm running mn with this command:

```
sudo mn --clean && sudo mn --controller=remote,ip=127.0.0.1,port=6633 --topo=linear,4 --switch=ovsk,protocols=OpenFlow13
```

It looks like this issue is related to the version of openvswitch. For example, I can't reproduce this issue on openvswitch 2.9.0-1. However, it reproduces deterministically with openvswitch 2.5.2, which is the upstream version on ubuntu xenial. I recall that Renan has told me in the past about a particular detail of implementation regarding a OpenFlow bitmap negotiation that was not fully supported on ovs <= 2.5.X. Maybe this is the root cause of the issue. 

What version of openvswitch are you running @hdiogenes ?

**Comment by renanrodrigo** [comment]
@viniciusarcanjo @hdiogenes The issue about the bitmaps was addressed at the time, but the connection problem was in fact deterministic with the 2.5.X version.
When we did the bitmap corrections, the Wireshark OpenFlow dissector was checking and validating every packet related to the handshake, but it kept failing despite anything.

**Comment by hdiogenes** [comment]
Thank you very much @renanrodrigo, I didn't know it was an old issue! @viniciusarcanjo I think I'm not reproducing that because I'm using the mininet VM from their site, running an old openvswitch - 2.0.2. @renanrodrigo do you have any idea on how to solve this? Just avoid using 2.5.X?

**Comment by renanrodrigo** [comment]
It was the first we did at the time.
As neither older nor new versions of OVS behave like this, I'm prone to believe it's a bug. Further investigation is needed to attack the issue...
The main problem is that the "broken" version seems to be the stable version on Ubuntu now.

**Comment by hdiogenes** [comment]
Considering that this behavior only happens with a specific openvswitch version (2.5.2), we're closing this issue. If you really need to use this version, contact us or reopen the issue.
