### ISSUE TITLE
Several Kytos Errors Found when Creating and Deleting Multiple EVCs

### ISSUE THREAD

**Issue by dgarc330** [kytos/kytos#949]
We were running code to test the controller's ability to create and delete multiple EVCs one after another. The code we were using is the same as the one Antonio developed for testing the mef_eline and can be found here: https://github.com/ajoaoff/mef_eline/blob/tests/tests/integration/tests/test1.sh

The errors starting popping up after we had created and deleted a couple hundred EVCs, and then started showing up more recently after the creation of just a few EVCs.

I have put in bold the beginning of each error messages so they can be easily seen where each one starts and ends.

**kytos $> 2019-08-15 17:32:19,019 - INFO** [kytos/mef_eline] (Thread-126562) Box 0a99ae72cf454386ba5ab7031db228ed was updated.
2019-08-15 17:32:19,119 - INFO [kytos/mef_eline] (Thread-126570) Box 0a99ae72cf454386ba5ab7031db228ed was updated.
2019-08-15 17:32:19,170 - INFO [kytos/mef_eline] (Thread-126573) Removing fedbbb81601f4903b54fe2eab5e80d88
2019-08-15 17:32:19,179 - INFO [kytos/mef_eline] (Thread-126572) Box 0a99ae72cf454386ba5ab7031db228ed was updated.
Exception in thread Thread-126560:
Traceback (most recent call last):
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/src/kytos/kytos/core/helpers.py", line 72, in threaded_handler
    handler(*args)
  File "/var/lib/kytos/napps/kytos/storehouse/main.py", line 311, in event_update
    self._execute_callback(event, box, error)
  File "/var/lib/kytos/napps/kytos/storehouse/main.py", line 142, in _execute_callback
    event.content['callback'](event, data, error)
  File "/var/lib/kytos/napps/../napps/kytos/mef_eline/storehouse.py", line 104, in _save_evc_callback
    log.info(f'Box {data.box_id} was updated.')
AttributeError: 'bool' object has no attribute 'box_id'

**kytos $> 2019-08-15 17:32:15,122** - INFO [kytos/mef_eline] (Thread-126343) Box 0a99ae72cf454386ba5ab7031db228ed was updated.
2019-08-15 17:32:15,192 - INFO [kytos/mef_eline] (Thread-126345) Box 0a99ae72cf454386ba5ab7031db228ed was updated.
2019-08-15 17:32:15,205 - INFO [kytos/mef_eline] (Thread-126349) Removing f1e407a25faa47bbb6e3734ade50ff41
2019-08-15 17:32:15,332 - INFO [kytos/mef_eline] (Thread-126360) Box 0a99ae72cf454386ba5ab7031db228ed was updated.
Exception in thread Thread-126359:
Traceback (most recent call last):
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/src/kytos/kytos/core/helpers.py", line 72, in threaded_handler
    handler(*args)
  File "/var/lib/kytos/napps/kytos/storehouse/main.py", line 299, in event_update
    box = backend.retrieve(namespace, box_id)
  File "/var/lib/kytos/napps/../napps/kytos/storehouse/backends/fs.py", line 88, in retrieve
    return self._load_from_file(destination)
  File "/var/lib/kytos/napps/../napps/kytos/storehouse/backends/fs.py", line 56, in _load_from_file
    data = pickle.load(load_file)
EOFError: Ran out of input

**Exception in thread Thread-464:**
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/tmp/kytos/kytos/core/helpers.py", line 72, in threaded_handler
    handler(*args)
  File "/tmp/python-kytos/var/lib/kytos/napps/kytos/storehouse/main.py", line 267, in event_retrieve
    self._execute_callback(event, box, error)
  File "/tmp/python-kytos/var/lib/kytos/napps/kytos/storehouse/main.py", line 134, in _execute_callback
    event.content['callback'](event, data, error)
  File "/tmp/python-kytos/var/lib/kytos/napps/../napps/kytos/mef_eline/storehouse.py", line 85, in _get_box_callback
    log.debug(f'Box {self.box.box_id} was load from storehouse.')
AttributeError: 'bool' object has no attribute 'box_id'
2019-08-16 16:20:38,410 - ERROR [kytos.core.controller] (Thread-460) Exception on /api/kytos/mef_eline/v2/evc/ [POST]
Traceback (most recent call last):
  File "/tmp/python-kytos/lib64/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/tmp/python-kytos/lib64/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/tmp/python-kytos/lib64/python3.6/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/tmp/python-kytos/lib64/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/tmp/python-kytos/lib64/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/tmp/python-kytos/lib64/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/tmp/python-kytos/lib64/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/tmp/python-kytos/var/lib/kytos/napps/kytos/mef_eline/main.py", line 126, in create_circuit
    evc.deploy()
  File "/tmp/python-kytos/var/lib/kytos/napps/../napps/kytos/mef_eline/models.py", line 457, in deploy
    success = self.deploy_to_backup_path()
  File "/tmp/python-kytos/var/lib/kytos/napps/../napps/kytos/mef_eline/models.py", line 427, in deploy_to_backup_path
    return self.deploy_to_path()
  File "/tmp/python-kytos/var/lib/kytos/napps/../napps/kytos/mef_eline/models.py", line 552, in deploy_to_path
    self.sync()
  File "/tmp/python-kytos/var/lib/kytos/napps/../napps/kytos/mef_eline/models.py", line 234, in sync
    self._storehouse.save_evc(self)
  File "/tmp/python-kytos/var/lib/kytos/napps/../napps/kytos/mef_eline/storehouse.py", line 89, in save_evc
    self.box.data[evc.id] = evc.as_dict()
AttributeError: 'bool' object has no attribute 'data'

**Exception in thread Thread-18977:**
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/tmp/kytos/kytos/core/helpers.py", line 72, in threaded_handler
    handler(*args)
  File "/tmp/python-kytos/var/lib/kytos/napps/kytos/storehouse/main.py", line 267, in event_retrieve
    self._execute_callback(event, box, error)
  File "/tmp/python-kytos/var/lib/kytos/napps/kytos/storehouse/main.py", line 134, in _execute_callback
    event.content['callback'](event, data, error)
  File "/tmp/python-kytos/var/lib/kytos/napps/../napps/kytos/mef_eline/storehouse.py", line 85, in _get_box_callback
    log.debug(f'Box {self.box.box_id} was load from storehouse.')
AttributeError: 'bool' object has no attribute 'box_id'

**Comment by ajoaoff** [comment]
I'm closing this issue here and reopening it in the `storehouse` repo, as the problem seems to be there.
