### ISSUE TITLE
Refactor `Controller.set_switch_options`: use config cache

### ISSUE THREAD

**Issue by hdiogenes** [kytos/kytos#960]
In #877, we noticed that when `of_core` calls the Kytos controller to instantiate a new switch, the controller re-parses `kytos.conf` to get the `vlan_pool` value again. This is not necessary - the configuration should already be loaded in memory, not parsed again. 

```
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "~/kytos/kytos/core/helpers.py", line 72, in threaded_handler
    handler(*args)
  File "~/venv/var/lib/kytos/napps/kytos/of_core/main.py", line 112, in handle_features_reply
    switch = version_utils.handle_features_reply(self.controller, event)
  File "~/venv/var/lib/kytos/napps/../napps/kytos/of_core/v0x04/utils.py", line 71, in handle_features_reply
    connection=connection)
  File "~/kytos/kytos/core/controller.py", line 542, in get_switch_or_create
    self.set_switch_options(dpid=dpid)
  File "~/kytos/kytos/core/controller.py", line 569, in set_switch_options
    vlan_pool = json.loads(self.options.vlan_pool)
  File "/usr/lib/python3.6/json/__init__.py", line 348, in loads
    'not {!r}'.format(s.__class__.__name__))
TypeError: the JSON object must be str, bytes or bytearray, not 'dict' 
```

**Comment by hdiogenes** [comment]
The relevant lines in the traceback above are these:

```
  File "~/kytos/kytos/core/controller.py", line 569, in set_switch_options
    vlan_pool = json.loads(self.options.vlan_pool)
```

In the same `controller` file, the `self.options` attribute definition has this comment:
```
        #: Object generated by ParseArgs on config.py file
        self.options = options
```

Which means that the `json.loads` operation should probably be moved to `config.KytosConfig.parse_args`.
